import { Session } from "@supabase/supabase-js";
import { useAtom } from "jotai";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { authAtom, isAuthenticatedAtom, userSessionAtom } from "../atoms/authenticatedAtom";
import Auth from "../components/Auth";
import { useAuth } from "../hooks/useAuth";
import { supabase } from "../utils/supabaseClient";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  const [session] = useAtom(authAtom);

  useAuth();

  return (
    <>
      <Head>25
        <title>Echo, Better Twitter Maybe?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl font-bold">Echo</h1>
        <p className="text-gray-500">Better Twitter Maybe?</p>
      </main>
      {
        session.isAuthenticated ? (
          <div>
            <h1>Logged in {session.userSession?.user.email}</h1>
            {/* A logout button */}
            <button
              className="w-full px-4 py-2 font-bold text-white bg-blue-500 rounded-lg hover:bg-blue-700 focus:outline-none focus:shadow-outline"
              onClick={async () => {
                await supabase.auth.signOut()
              }}
            >Log Out</button>
          </div>
        ) : (
          <Auth />
        )
      }
    </>
  );
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

export default Home;
